version: '3.8'

services:
  gateway-service:
    build:
      context: ./gateway-service
    ports:
      - "80:3000"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=mlaku_mulu
      - JWT_SECRET=${JWT_SECRET}
      - AUTH_SERVICE_URL=auth-service:50051
      - TRAVEL_SERVICE_URL=travel-service:50052
    depends_on:
      - postgres

  auth-service:
    build:
      context: ./auth-service
    ports:
      - "50051:50051"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=mlaku_mulu
      - JWT_SECRET=${JWT_SECRET}
      - GATEWAY_SERVICE_URL=gateway-service:3000
      - AUTH_SERVICE_URL=0.0.0.0:50051
    depends_on:
      - postgres

  travel-service:
    build:
      context: ./travel-service
    ports:
      - "50052:50052"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=mlaku_mulu
      - JWT_SECRET=${JWT_SECRET}
      - GATEWAY_SERVICE_URL=gateway-service:3000
      - TRAVEL_SERVICE_URL=auth-service:50052
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mlaku_mulu
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: